import random
import sys


def recv_from_sock(sock):
    """ Receives and returns 4096 bytes from socket in BLOCKING mode.

    Parameters:
        sock: socket """
    return sock.recv(4096)


def get_ip_addr(sock):
    """ Get peer IP address from a socket sock and returns it as bytes.

    Parameters:
        sock: socket """
    return bytes(sock.getpeername()[0], encoding=sys.getdefaultencoding())


def gen_rand_bytes_w10(len):
    """ Returns randomly generated byte string from values 0-255 without 10.

    Parameters:
        len: int """
    bytevals = list(range(256))
    bytevals.remove(10)  # LF
    return bytes([random.choice(bytevals) for _ in range(len)])
